version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: test_task
    restart: always
    environment:
      POSTGRES_DB: test_task
      POSTGRES_USER: test_task
      POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"

volumes:
  postgres_data:
